# Generated by Django 4.2.28 on 2026-02-09 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='whatsapp_number',
            field=models.CharField(blank=True, db_index=True, help_text='Numéro WhatsApp international ex: 22890000000', max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro WhatsApp invalide. Utilise uniquement des chiffres.', regex='^\\d{8,15}$')]),
        ),
    ]
