# Generated by Django 4.2.28 on 2026-02-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visit',
            name='stats_visit_action_edd936_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='stats_visit_shop_id_c45dc8_idx',
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['shop', 'action', 'created_at'], name='stats_visit_shop_id_1935aa_idx'),
        ),
    ]
